# Generated by Django 5.1 on 2024-11-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='league',
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
