# Generated by Django 5.1 on 2024-11-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=33)),
                ('title', models.CharField(max_length=51)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='banners/')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
