# Generated by Django 5.1 on 2024-11-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_product_delete_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='photo',
        ),
    ]
