# Generated by Django 5.1 on 2024-12-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_bot_register',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
