# Generated by Django 5.1 on 2024-12-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_admin_user_telegram_bot_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'To‘langan'), ('unpaid', 'To‘lanmagan')], default='unpaid', max_length=10),
        ),
    ]
