# Generated by Django 5.1 on 2025-04-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_last_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS')], max_length=10)),
            ],
        ),
    ]
